version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - cargo-cache:/usr/local/cargo/registry
    # Use cargo-watch to auto-restart on changes
    command: cargo install cargo-watch && cargo watch -x run

volumes:
  cargo-cache:
