name: Deploy to Google Cloud Run

on:
  push:
    branches: [main, uat]

env:
  PROJECT_ID: actota
  SERVICE_NAME: actota-api
  REGION: us-central1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    # Add environment based on branch
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'uat' }}
    
    permissions:
      contents: read
      id-token: write # Needed for auth with Google Cloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables for deployment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "DEPLOYMENT_ENV=production" >> $GITHUB_ENV
            echo "MIN_INSTANCES=1" >> $GITHUB_ENV
            echo "MAX_INSTANCES=10" >> $GITHUB_ENV
            echo "MEMORY=1Gi" >> $GITHUB_ENV
            echo "CPU=1" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_ENV=uat" >> $GITHUB_ENV
            echo "MIN_INSTANCES=0" >> $GITHUB_ENV
            echo "MAX_INSTANCES=5" >> $GITHUB_ENV
            echo "MEMORY=512Mi" >> $GITHUB_ENV
            echo "CPU=1" >> $GITHUB_ENV
          fi
          echo "IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}-${{ env.DEPLOYMENT_ENV }}" >> $GITHUB_ENV

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build and Push Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}-${{ env.DEPLOYMENT_ENV }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          flags: |
            --allow-unauthenticated
            --service-account=${{ secrets.SERVICE_ACCOUNT }}
            --memory=${{ env.MEMORY }}
            --cpu=${{ env.CPU }}
            --min-instances=${{ env.MIN_INSTANCES }}
            --max-instances=${{ env.MAX_INSTANCES }}
            --concurrency=80
            --timeout=300s
            
      - name: Set environment variables from secrets
        run: |
          # Create a temporary env file from secrets
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> temp.env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> temp.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> temp.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> temp.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> temp.env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> temp.env
          echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> temp.env
          echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> temp.env
          echo "FACEBOOK_REDIRECT_URI=${{ secrets.FACEBOOK_REDIRECT_URI }}" >> temp.env
          
      - name: Update service with environment variables
        run: |
          # Install gcloud
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-cli
          
          # Format environment variables for deployment
          ENV_VARS=""
          while IFS= read -r line || [[ -n "$line" ]]; do
              # Skip empty lines and comments
              if [[ -n "$line" && ! "$line" =~ ^\# ]]; then
                  # Add the line as an environment variable
                  ENV_VARS="${ENV_VARS} --set-env-vars=${line}"
              fi
          done < temp.env
          
          # Update the service with environment variables
          gcloud run services update ${{ env.SERVICE_NAME }}-${{ env.DEPLOYMENT_ENV }} \
            --platform managed \
            --region ${{ env.REGION }} \
            ${ENV_VARS}
            
          # Cleanup
          rm temp.env
          
      - name: Test deployment
        run: |
          curl -s "${{ steps.deploy.outputs.url }}/health" | jq
          
      - name: Show deployment URL
        run: |
          echo "Service deployed to ${{ steps.deploy.outputs.url }}"