name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
      - uat
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: actota-api
  REGION: us-central1
  # Define these here for clarity, they will be accessed correctly in the job steps
  RUST_ENV: ${{vars.RUST_ENV}}
  FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
  FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
  STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET}}
  CLOUD_STORAGE_URL: ${{vars.CLOUD_STORAGE_URL}}
  FACEBOOK_REDIRECT_URI: ${{vars.FACEBOOK_REDIRECT_URI}}
  GOOGLE_REDIRECT_URI: ${{vars.GOOGLE_REDIRECT_URI}}
  FRONTEND_URL: ${{vars.FRONTEND_URL}}
  ITINERARY_BUCKET: ${{vars.ITINERARY_BUCKET}}
  PROFILE_PIC_BUCKET: ${{vars.PROFILE_PIC_BUCKET}}
  RUST_LOG: ${{vars.RUST_LOG}}
jobs:
  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Build the Docker image, passing only build-time arguments
      - name: Build
        run: |
          docker build \
            --build-arg RUST_ENV="${{ env.RUST_ENV }}" \
            --build-arg RUST_LOG="${{ env.RUST_LOG }}" \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
      # Create or update secrets in Secret Manager
      - name: Create/Update Secrets
        run: |
          # Create Secret Manager secrets if they don't exist
          echo -n "${{ env.FACEBOOK_CLIENT_SECRET }}" | \
            gcloud secrets create facebook-client-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.FACEBOOK_CLIENT_SECRET }}" | \
            gcloud secrets versions add facebook-client-secret --data-file=-

          echo -n "${{ env.GOOGLE_CLIENT_SECRET }}" | \
            gcloud secrets create google-client-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.GOOGLE_CLIENT_SECRET }}" | \
            gcloud secrets versions add google-client-secret --data-file=-

          echo -n "${{ env.JWT_SECRET }}" | \
            gcloud secrets create jwt-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.JWT_SECRET }}" | \
            gcloud secrets versions add jwt-secret --data-file=-

          echo -n "${{ env.MONGODB_URI }}" | \
            gcloud secrets create mongodb-uri --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.MONGODB_URI }}" | \
            gcloud secrets versions add mongodb-uri --data-file=-

          echo -n "${{ env.STRIPE_SECRET_KEY }}" | \
            gcloud secrets create stripe-secret-key --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.STRIPE_SECRET_KEY }}" | \
            gcloud secrets versions add stripe-secret-key --data-file=-

          echo -n "${{ env.STRIPE_WEBHOOK_SECRET }}" | \
            gcloud secrets create stripe-webhook-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.STRIPE_WEBHOOK_SECRET }}" | \
            gcloud secrets versions add stripe-webhook-secret --data-file=-
      - name: Deploy
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --platform managed \
            --service-account=actota-api@${PROJECT_ID}.iam.gserviceaccount.com \
            --set-env-vars=FACEBOOK_CLIENT_ID="${{ env.FACEBOOK_CLIENT_ID }}" \
            --set-env-vars=GOOGLE_CLIENT_ID="${{ env.GOOGLE_CLIENT_ID }}" \
            --set-env-vars=CLOUD_STORAGE_URL="${{ env.CLOUD_STORAGE_URL }}" \
            --set-env-vars=FACEBOOK_REDIRECT_URI="${{ env.FACEBOOK_REDIRECT_URI }}" \
            --set-env-vars=GOOGLE_REDIRECT_URI="${{ env.GOOGLE_REDIRECT_URI }}" \
            --set-env-vars=FRONTEND_URL="${{ env.FRONTEND_URL }}" \
            --set-env-vars=ITINERARY_BUCKET="${{ env.ITINERARY_BUCKET }}" \
            --set-env-vars=PROFILE_PIC_BUCKET="${{ env.PROFILE_PIC_BUCKET }}" \
            --set-env-vars=RUST_ENV="${{ env.RUST_ENV }}" \
            --set-env-vars=RUST_LOG="${{ env.RUST_LOG }}" \
            --set-env-vars=SERVICE_ACCOUNT_JSON="{\"_\":\"_\"}" \
            --set-secrets=FACEBOOK_CLIENT_SECRET=facebook-client-secret:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,JWT_SECRET=jwt-secret:latest,MONGODB_URI=mongodb-uri:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest \
            --allow-unauthenticated

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Build
        run: |
          docker build \
            --build-arg RUST_ENV="${{ env.RUST_ENV }}" \
            --build-arg RUST_LOG="${{ env.RUST_LOG }}" \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
      # Create or update secrets in Secret Manager
      - name: Create/Update Secrets
        run: |
          # Create Secret Manager secrets if they don't exist
          echo -n "${{ env.FACEBOOK_CLIENT_SECRET }}" | \
            gcloud secrets create facebook-client-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.FACEBOOK_CLIENT_SECRET }}" | \
            gcloud secrets versions add facebook-client-secret --data-file=-

          echo -n "${{ env.GOOGLE_CLIENT_SECRET }}" | \
            gcloud secrets create google-client-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.GOOGLE_CLIENT_SECRET }}" | \
            gcloud secrets versions add google-client-secret --data-file=-

          echo -n "${{ env.JWT_SECRET }}" | \
            gcloud secrets create jwt-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.JWT_SECRET }}" | \
            gcloud secrets versions add jwt-secret --data-file=-

          echo -n "${{ env.MONGODB_URI }}" | \
            gcloud secrets create mongodb-uri --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.MONGODB_URI }}" | \
            gcloud secrets versions add mongodb-uri --data-file=-

          echo -n "${{ env.STRIPE_SECRET_KEY }}" | \
            gcloud secrets create stripe-secret-key --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.STRIPE_SECRET_KEY }}" | \
            gcloud secrets versions add stripe-secret-key --data-file=-

          echo -n "${{ env.STRIPE_WEBHOOK_SECRET }}" | \
            gcloud secrets create stripe-webhook-secret --data-file=- --replication-policy="automatic" || \
            echo -n "${{ env.STRIPE_WEBHOOK_SECRET }}" | \
            gcloud secrets versions add stripe-webhook-secret --data-file=-
      - name: Deploy
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --platform managed \
            --service-account=actota-api@${PROJECT_ID}.iam.gserviceaccount.com \
            --set-env-vars=FACEBOOK_CLIENT_ID="${{ env.FACEBOOK_CLIENT_ID }}" \
            --set-env-vars=GOOGLE_CLIENT_ID="${{ env.GOOGLE_CLIENT_ID }}" \
            --set-env-vars=CLOUD_STORAGE_URL="${{ env.CLOUD_STORAGE_URL }}" \
            --set-env-vars=FACEBOOK_REDIRECT_URI="${{ env.FACEBOOK_REDIRECT_URI }}" \
            --set-env-vars=GOOGLE_REDIRECT_URI="${{ env.GOOGLE_REDIRECT_URI }}" \
            --set-env-vars=FRONTEND_URL="${{ env.FRONTEND_URL }}" \
            --set-env-vars=ITINERARY_BUCKET="${{ env.ITINERARY_BUCKET }}" \
            --set-env-vars=PROFILE_PIC_BUCKET="${{ env.PROFILE_PIC_BUCKET }}" \
            --set-env-vars=RUST_ENV="${{ env.RUST_ENV }}" \
            --set-env-vars=RUST_LOG="${{ env.RUST_LOG }}" \
            --set-env-vars=SERVICE_ACCOUNT_JSON="{\"_\":\"_\"}" \
            --set-secrets=FACEBOOK_CLIENT_SECRET=facebook-client-secret:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,JWT_SECRET=jwt-secret:latest,MONGODB_URI=mongodb-uri:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest \
            --allow-unauthenticated
